version: 2

dbt_earthquake:
  outputs:
    dev:
      type: snowflake
      account: 
      user: 
      password: 
      role: accountadmin
      database: earthquake
      warehouse: 
      schema: dbt
      threads: 10
      client_session_keep_alive: False
  target: dev
